<div class="nearbyPage textPageCont">

	<div class="container-fluid padding-25 sm-padding-10" style="padding-top:0px !important;">
		<div class="panel newpanel m-t-10 textPage">
			<div class="categoryHeadingRow">
				<h5>Terms and Conditions</h5>
			</div>
			<p>Welcome to Swolk’s Terms of Service. Please read this carefully before using our site, services, or products. This is a contract between you and Swolk. We've also included several annotations that aren't a part of the contract itself, but are intended to emphasize key sections and help you follow the text. We’ve tried to be fair and straightforward. Please feel free to contact us at our email via <a href="mailto:swolk.com@gmail.com">swolk.com@gmail.com</a>, if you have any questions or suggestions!</p>
			<h6>1. Accepting the Terms of Service</h6>
			<p>Please read these Terms of Service (collectively, the "Agreement") carefully before using Swolk.com (the "Site") and/or the other domains, websites, products, applications, mobile applications, services, and/or Content provided by Swolk.com. (all of those collectively with the Site, the "Services"). By using or accessing the Services, you ("Subscriber" or "you") agree to be bound by all the terms and conditions of this Agreement. If you don’t agree to all the terms and conditions of this Agreement, you shouldn't, and aren't permitted to, use the Services.</p>
			<h6>2. Modifications to this Agreement</h6>
			<p>Swolk reserves the right to modify this Agreement by (1) posting a revised Agreement on and/or through the Services and (2) providing notice to you that this Agreement has changed, generally via email where practicable, and otherwise through the Services (such as through a notification on your Swolk Dashboard or in our mobile applications). Modifications will not apply retroactively. You are responsible for reviewing and becoming familiar with any modifications to this Agreement.</p>
			<p>We may sometimes ask you to review and to explicitly agree to (or reject) a revised version of this Agreement. In such cases, modifications will be effective at the time of your agreement to the modified version of this Agreement. If you do not agree at that time, you are not permitted to use the Services.</p>
			<p>In cases where we do not ask for your explicit agreement to a modified version of this Agreement, but otherwise provide notice as set forth above, the modified version of this Agreement will become effective fourteen days after we have posted the modified Agreement and provided you notification of the modifications. Your use of the Services following that period constitutes your acceptance of the terms and conditions of this Agreement as modified. If you do not agree to the modifications, you are not permitted to use, and should discontinue your use of, the Services.</p>
			<p>Note that, if you have prepaid for any Paid Services (as defined below) prior to a modification of this Agreement, your use of such prepaid Paid Services is governed by the version of this Agreement in effect at the time Swolk received your prepayment.</p>
			<p>As Swolk grows and improves, we might have to make changes to these Terms of Service. When we do, we'll let you know. We're also going to make it a practice to post old versions so it's easy to see changes/additions/deletions. To see old versions, scroll down to the end of this document.</p>
			<h6>3. Use of the Services</h6>
			<p><strong>Eligibility:</strong> No individual under the age of thirteen (13) may use the Services, provide any personal information to Swolk, or otherwise submit personal information through the Services (including, for example, a name, address, telephone number, or email address). You may only use the Services if you can form a binding contract with Swolk and are not legally prohibited from using the Services.</p>
			<p><strong>Service Changes and Limitations:</strong> The Services change frequently, and their form and functionality may change without prior notice to you. Swolk retains the right to create limits on and related to use of the Services in its sole discretion at any time with or without notice. Swolk may also impose limits on certain Services or aspects of those Services or restrict your access to parts or all of the Services without notice or liability. Swolk may change, suspend, or discontinue any or all of the Services at any time, including the availability of any product, feature, database, or Content (as defined below). Swolk may also terminate or suspend Accounts (as defined below) at any time, in its sole discretion.</p>
			<p><strong>Limitations on Automated Use:</strong> You may not, without express prior written permission, do any of the following while accessing or using the Services: (a) tamper with, or use non-public areas of the Services, or the computer or delivery systems of Swolk and/or its service providers; (b) probe, scan, or test any system or network (particularly for vulnerabilities), or otherwise attempt to breach or circumvent any security or authentication measures; (c) access or search or attempt to access or search the Services by any means (automated or otherwise) other than through our currently available, published interfaces that are provided by Swolk (and only pursuant to those terms and conditions) or unless permitted by Swolk's robots.txt file or other robot exclusion mechanisms; (d) scrape the Services, and particularly scrape Content (as defined below) from the Services; (e) use the Services to send altered, deceptive, or false source-identifying information, including without limitation by forging TCP-IP packet headers or email headers; or (f) interfere with, or disrupt, (or attempt to do so), the access of any Subscriber, host or network, including, without limitation, by sending a virus to, spamming, or overloading the Services, or by scripted use of the Services in such a manner as to interfere with or create an undue burden on the Services.</p>
			<p>Don't do bad things to Swolk or to other users. Some particularly egregious examples of "bad things" are listed in this section.</p>
			<h6>4. Registration, Swolk URLs, and Security</h6>
			<p>As a condition to using certain of the Services, you may be required to create an account (an "Account") and select a password and Swolk username, which will serve as a default link to your default Swolk blog of the form [username].Swolk.com (a "Swolk URL"). You must select a different Swolk URL for each new blog you create.</p>
			<p>You agree to provide Swolk with accurate, complete, and updated registration information, particularly your email address.</p>
			<p>It's really important that the email address associated with your Swolk account is accurate and up-to-date. If you ever forget your password - or worse, fall victim to a malicious phishing attack - a working email address is often the only way for us to recover your account.</p>
			<p>You are also responsible for maintaining the confidentiality of your Account password and for the security of your Account, and you will notify Swolk immediately of any actual or suspected loss, theft, or unauthorized use of your Account or Account password.</p>
			<h6>5. Privacy</h6>
			<p>For information about how Swolk collects, uses, and shares your information, please review our Privacy Policy. You agree that by using the Services you consent to the collection, use, and sharing (as set forth in the Privacy Policy) of such information, including the transfer of this information to the United States and/or other countries for storage, processing, and use by Swolk and the Swolk Affiliates (as defined below).</p>
			<h6>6. Content and Subscriber Content</h6>
			<p><strong>Definitions:</strong> For purposes of this Agreement: (1) the term "Content" means a creative expression and includes, without limitation, video, audio, photographs, images, illustrations, animations, logos, tools, written posts, replies, comments, information, data, text, software, scripts, executable files, graphics, Themes (as defined below), and interactive features, any of which may be generated, provided, or otherwise made accessible on or through the Services; (2) the term "Subscriber Content" means Content that a Subscriber submits, transfers, or otherwise provides to the Services. Content includes, without limitation, all Subscriber Content.</p>
			<p><strong>Your Rights in Subscriber Content:</strong> Subscribers retain ownership and/or other applicable rights in Subscriber Content, and Swolk and/or third parties retain ownership and/or other applicable rights in all Content other than Subscriber Content. You retain ownership you have of any intellectual property you post to Swolk.</p>
			<p><strong>Subscriber Content License to Swolk:</strong> When you provide Subscriber Content to Swolk through the Services, you grant Swolk a non-exclusive, worldwide, royalty-free, sublicensable, transferable right and license to use, host, store, cache, reproduce, publish, display (publicly or otherwise), perform (publicly or otherwise), distribute, transmit, modify, adapt (including, without limitation, in order to conform it to the requirements of any networks, devices, services, or media through which the Services are available), and create derivative works of, such Subscriber Content. The rights you grant in this license are for the limited purposes of allowing Swolk to operate the Services in accordance with their functionality, improve the Services, and develop new Services. The reference in this license to "creat[ing] derivative works" is not intended to give Swolk a right to make substantive editorial changes or derivations, but does, for example, enable reshare, which allows Swolk Subscribers to redistribute Subscriber Content from one Swolkprofile page to another in a manner that allows them to add their own text or other Content before or after your Subscriber Content.</p>
			<p>You also agree that this license includes the right for Swolk to make all publicly-posted Content available to third parties selected by Swolk, so that those third parties can syndicate and/or analyze such Content on other media and services.</p>
			<p>An example of what it means to "make all publicly-posted Content available" to a Swolk partner for distribution or analysis would be licensing the Swolk "firehose," a live feed of all public activity on Swolk, to partners like search engines.</p>
			<p>Note also that this license to your Subscriber Content continues even if you stop using the Services, primarily because of the social nature of Content shared through Swolk’s Services - when you post something publicly, others may choose to comment on it, making your Content part of a social conversation that can’t later be erased without retroactively censoring the speech of others.</p>
			<p>One thing you should consider before posting: When you make something publicly available on the Internet, it becomes practically impossible to take down all copies of it.</p>
			<p><strong>Content License to You:</strong> As a Subscriber of the Services, Swolk grants you a worldwide, revocable, non-exclusive, non-sublicensable, and non-transferable license to download, store, view, display, perform, redistribute, and create derivative works of Content solely in connection with your use of, and in strict accordance with the functionality and restrictions of, the Services (including, without limitation, Paid Services, as defined below). This means, for example, that we license Content to you for purposes of re-sharing.</p>
			<p><strong>Compliance with Community Guidelines:</strong> You agree that you won't violate Swolk'sCommunity Guidelines.</p>
			<p><strong>Termination and Deletion:</strong> On termination of your Account, or upon your deletion of particular pieces of Subscriber Content from the Services, Swolk shall make reasonable efforts to make such Subscriber Content inaccessible and cease use of it; however, you acknowledge and agree that: (a) removed Subscriber Content may persist in caches or backups for a reasonable period of time and (b) copies of or references to the Subscriber Content may not be entirely removed (due to the nature of reblogging, for example).</p>
			<h6>7. Time Limitation on Claims and Releases From Liability</h6>
			<p>You agree that any claim you may have arising out of or related to this Agreement or your relationship with Swolk must be filed within one year after such claim arose; otherwise, your claim is permanently barred. You further release, to the fullest extent permitted by law, Swolk and its employees, agents, consultants, directors, shareholders, any other person or entity that directly or indirectly controls, is under common control with, or is directly or indirectly controlled by, Swolk (the “Swolk Affiliates”) from responsibility, liability, claims, demands, and/or damages (actual and consequential) of every kind and nature, known and unknown (including but not limited to claims of negligence), arising out of or related to the following:</p>
			<ul>
				<li>Disputes between Subscribers, including those between you and other Subscribers.</li>
				<li>The acts of third parties generally (i.e., individuals or entities who are not Swolk or a Swolk Affiliate), including third party sites and services.</li>
				<li>Disputes concerning any use of or action taken using your Account by you or a third party.</li>
				<li>Claims relating to the unauthorized access to any data communications relating to, or Content stored under or relating to, your Account, including but not limited to unauthorized interception, use, or alteration of such communications or your Content. For the sake of clarity, this includes any and all claims related to the security of your Account credentials.</li>
				<li>Claims relating to any face-to-face meetings in any way related to Swolk at any venues ("Meetups"), including without limitation claims related to the actions or omissions of any Subscribers or third parties who organize, attend, or are otherwise involved in any Meetups; see our Meetups page for more information. Unless otherwise expressly disclosed in writing, Swolk does not sponsor, oversee, or in any manner control Meetups.</li>
			</ul>
			<p>
				If you are a California resident, you waive California Civil Code § 1542, which says: "A general release does not extend to claims which the creditor does not know or suspect to exist in his favor at the time of executing the release, which if known by him must have materially affected his settlement with the debtor."
			</p>
			<h6>8. Limitation of Liability</h6>
			<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, SWOLK AND THE SWOLK AFFILIATES SHALL NOT BE LIABLE FOR: (A) ANY INDIRECT, INCIDENTAL, EXEMPLARY PUNITIVE, OR CONSEQUENTIAL DAMAGES OF ANY KIND WHATSOEVER; (B) LOSS OF: PROFITS, REVENUE, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES; (C) DAMAGES RELATING TO YOUR ACCESS TO, USE OF, OR INABILITY TO ACCESS OR USE THE SERVICES; (D) DAMAGES RELATING TO ANY CONDUCT OR CONTENT OF ANY THIRD PARTY OR SUBSCRIBER USING THE SERVICES, INCLUDING WITHOUT LIMITATION, DEFAMATORY, OFFENSIVE OR ILLEGAL CONDUCT OR CONTENT; AND/OR (E) DAMAGES IN ANY MANNER RELATING TO ANY CONTENT. THIS LIMITATION APPLIES TO ALL CLAIMS, WHETHER BASED ON WARRANTY, CONTRACT, TORT, OR ANY OTHER LEGAL THEORY, WHETHER OR NOT SWOLK HAS BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, AND FURTHER WHERE A REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED ITS ESSENTIAL PURPOSE.</p>
			<p>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE TOTAL LIABILITY OF SWOLK AND THE SWOLK AFFILIATES, FOR ANY CLAIM UNDER THIS AGREEMENT, INCLUDING FOR ANY IMPLIED WARRANTIES, IS LIMITED TO THE GREATER OF ONE HUNDRED DOLLARS (US $100.00) OR THE AMOUNT YOU PAID US TO USE THE APPLICABLE SERVICE(S).</p>
			<h6>9. Exclusions to Warranties and Limitation of Liability</h6>
			<p>Some jurisdictions may not allow the exclusion of certain warranties or the exclusion/limitation of liability as set forth in Section 14, so the limitations above may not apply to you.</p>
			<h6>10. Termination</h6>
			<p>Either party may terminate this Agreement at any time by notifying the other party. Swolk may terminate or suspend your access to or ability to use any and all Services immediately, without prior notice or liability, for any reason or no reason, including but not limited to if you breach any of the terms or conditions of this Agreement. In particular, Swolk may immediately terminate or suspend Accounts that have been flagged for repeat copyright infringement.<br/>
			Upon termination of your access to or ability to use a Service, including but not limited to suspension of your Account on a Service, your right to use or access that Service and any Content will immediately cease. All provisions of this Agreement that by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, and limitations of liability. Termination of your access to and use of the Services shall not relieve you of any obligations arising or accruing prior to such termination or limit any liability that you otherwise may have to Swolk or any third party.</p>
			<h6>11. Choice of Law and Venue</h6>
			<p>You and Swolk agree that we will resolve any claim or controversy at law or equity that arises out of this Agreement or the Services in accordance with this Section or as you and Swolk otherwise agree in writing. Before resorting to formal dispute resolution, we strongly encourage you to contact us via email at <a href="mailto:swolk.com@gmail.com">swolk.com@gmail.com</a> to seek a resolution.</p>
			<p><strong>Law and Forum for Legal Disputes:</strong> This Agreement shall be governed in all respects by the laws of the State of New York as they apply to agreements entered into and to be performed entirely within New York between New York residents, without regard to conflict of law provisions. You agree that any claim or dispute you may have against Swolk must be resolved exclusively by a state or federal court located in New York County, New York, except as otherwise agreed by the parties. You agree to submit to the personal jurisdiction of the courts located within New York County, New York for the purpose of litigating all such claims or disputes.</p>
			<p>If you are (a) a United States federal, state, or local government agency or body, (b) using the Services in your official capacity, and (c) legally unable to accept the clauses in this Section, then this Section doesn’t apply to you. For such entities, this Agreement and any related action will be governed by the laws of the United States of America, without regard to conflict of law provisions, and, in the absence of federal law and to the extent permitted under federal law, the laws of the State of New York, excluding choice of law.</p>
			<h6>12. Miscellaneous</h6>
			<p>This Agreement, as modified from time to time, constitutes the entire agreement between you and Swolk with respect to the subject matter hereof. This Agreement replaces all prior or contemporaneous understandings or agreements, written or oral, regarding the subject matter hereof and constitutes the entire and exclusive agreement between the parties. The failure of either party to exercise, in any way, any right provided for herein shall not be deemed a waiver of any further rights hereunder. If any provision of this Agreement is found to be unenforceable or invalid, that provision shall be limited or eliminated to the minimum extent necessary so that this Agreement shall otherwise remain enforceable and in full force and effect. This Agreement is not assignable, transferable, or sublicensable by you except with Swolk's prior written consent. Swolk may assign this Agreement in whole or in part at any time without your consent. No agency, partnership, joint venture, or employment is created as a result of this Agreement and you do not have any authority of any kind to bind Swolk in any respect whatsoever.</p>
		</div>
	</div>	
</div>

	
